//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SvHoo.Service.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class BannerLocation
    {
        public int SysNo { get; set; }
        public Nullable<int> BannerSysNo { get; set; }
        public Nullable<int> PageID { get; set; }
        public Nullable<System.DateTime> BeginDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public Nullable<int> Proiority { get; set; }
        public string Status { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
    }
}
