//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SvHoo.Service.Database
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DatabaseEntities : DbContext
    {
        public DatabaseEntities()
            : base("name=DatabaseEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Area> Area { get; set; }
        public DbSet<Banner> Banner { get; set; }
        public DbSet<BannerLocation> BannerLocation { get; set; }
        public DbSet<Booking> Booking { get; set; }
        public DbSet<BookingItem> BookingItem { get; set; }
        public DbSet<Category> Category { get; set; }
        public DbSet<Customer> Customer { get; set; }
        public DbSet<CustomerExt> CustomerExt { get; set; }
        public DbSet<CustomerOrder> CustomerOrder { get; set; }
        public DbSet<News> News { get; set; }
        public DbSet<NewsType> NewsType { get; set; }
        public DbSet<Order> Order { get; set; }
        public DbSet<OrderItem> OrderItem { get; set; }
        public DbSet<Product> Product { get; set; }
        public DbSet<ProductProperty> ProductProperty { get; set; }
        public DbSet<ProductReview> ProductReview { get; set; }
        public DbSet<Property> Property { get; set; }
        public DbSet<PropertyValue> PropertyValue { get; set; }
        public DbSet<Seller> Seller { get; set; }
        public DbSet<SellerAction> SellerAction { get; set; }
        public DbSet<SellerRole> SellerRole { get; set; }
        public DbSet<SellerRoleAction> SellerRoleAction { get; set; }
        public DbSet<SellerUser> SellerUser { get; set; }
        public DbSet<Stores> Stores { get; set; }
        public DbSet<StoresUser> StoresUser { get; set; }
        public DbSet<SysAction> SysAction { get; set; }
        public DbSet<SysConfig> SysConfig { get; set; }
        public DbSet<SysEventLog> SysEventLog { get; set; }
        public DbSet<SysRole> SysRole { get; set; }
        public DbSet<SysRoleAction> SysRoleAction { get; set; }
        public DbSet<SysUser> SysUser { get; set; }
    }
}
