//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SvHoo.Service.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public int SysNo { get; set; }
        public Nullable<int> StoresSysNo { get; set; }
        public Nullable<int> CustomerSysNo { get; set; }
        public Nullable<int> SellerUserSysNo { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public Nullable<System.DateTime> PreTime { get; set; }
        public Nullable<System.DateTime> UseTime { get; set; }
        public string Note { get; set; }
        public string Status { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
    }
}
