//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SvHoo.Service.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public int SysNo { get; set; }
        public Nullable<int> StoresSysNo { get; set; }
        public Nullable<int> CategorySysNo { get; set; }
        public string Title { get; set; }
        public string Code { get; set; }
        public string Name { get; set; }
        public Nullable<decimal> Price { get; set; }
        public string Note { get; set; }
        public string Detail { get; set; }
        public Nullable<bool> Recommend { get; set; }
        public Nullable<int> Priority { get; set; }
        public string Status { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
    }
}
