//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SvHoo.Service.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class SysEventLog
    {
        public int SysNo { get; set; }
        public string Source { get; set; }
        public string Category { get; set; }
        public string IP { get; set; }
        public string HostName { get; set; }
        public Nullable<int> EventType { get; set; }
        public string EventTitle { get; set; }
        public string EventMessage { get; set; }
        public string EventDetail { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
    }
}
